"""create suggestions tables

Revision ID: 14e64b7e8655
Revises: 62cec1f81893
Create Date: 2025-12-12 16:43:49.895526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14e64b7e8655'
down_revision: Union[str, Sequence[str], None] = '62cec1f81893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_tenant_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_suggestion_audit_id'), table_name='suggestion_audit')
    op.drop_table('suggestion_audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suggestion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('suggestion_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('suggestion_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('before', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('after', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('translation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suggestion_audit_pkey'))
    )
    op.create_index(op.f('ix_suggestion_audit_id'), 'suggestion_audit', ['id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('suggestions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('translation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('source_language', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('suggestions_pkey'))
    )
    op.create_index(op.f('ix_suggestions_tenant_id'), 'suggestions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_suggestions_id'), 'suggestions', ['id'], unique=False)
    # ### end Alembic commands ###
