"""initial baseline after reset

Revision ID: 4e75750e4811
Revises: 
Create Date: 2025-10-18 14:03:17.033763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e75750e4811'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion_audit', sa.Column('translation_id', sa.String(), nullable=True))
    op.add_column('suggestion_audit', sa.Column('path', sa.String(), nullable=True))
    op.drop_column('suggestion_audit', 'segment_id')
    op.add_column('suggestions', sa.Column('translation_id', sa.String(), nullable=True))
    op.add_column('suggestions', sa.Column('path', sa.String(), nullable=True))
    op.drop_index(op.f('ix_suggestions_segment_id'), table_name='suggestions')
    op.drop_column('suggestions', 'segment_id')
    op.drop_column('translate', 'trans_accept')
    op.drop_column('translate', 'trans_edit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate', sa.Column('trans_edit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('translate', sa.Column('trans_accept', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suggestions', sa.Column('segment_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_suggestions_segment_id'), 'suggestions', ['segment_id'], unique=False)
    op.drop_column('suggestions', 'path')
    op.drop_column('suggestions', 'translation_id')
    op.add_column('suggestion_audit', sa.Column('segment_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('suggestion_audit', 'path')
    op.drop_column('suggestion_audit', 'translation_id')
    # ### end Alembic commands ###
