"""Add translation flags

Revision ID: 5f640b1fd316
Revises: b12e1fcf631b
Create Date: 2025-11-05 11:53:28.681275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f640b1fd316'
down_revision: Union[str, Sequence[str], None] = 'b12e1fcf631b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate', sa.Column('transAccept', sa.Boolean(), nullable=True))
    op.add_column('translate', sa.Column('transEdit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translate', 'transEdit')
    op.drop_column('translate', 'transAccept')
    # ### end Alembic commands ###
