"""changed language_pair with target_language and source_language

Revision ID: 62cec1f81893
Revises: 5f640b1fd316
Create Date: 2025-11-27 12:19:06.001572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cec1f81893'
down_revision: Union[str, Sequence[str], None] = '5f640b1fd316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('suggestions', sa.Column(
        'target_language', sa.String(length=32), nullable=True))
    op.add_column('suggestions', sa.Column(
        'source_language', sa.String(length=32), nullable=True))

    # Populate existing rows with temporary fallback values
    op.execute(
        "UPDATE suggestions SET target_language = 'en' WHERE target_language IS NULL;")
    op.execute(
        "UPDATE suggestions SET source_language = 'en' WHERE source_language IS NULL;")

    # Now enforce NOT NULL
    op.alter_column('suggestions', 'target_language', nullable=False)
    op.alter_column('suggestions', 'source_language', nullable=False)

    op.drop_column('suggestions', 'language_pair')

# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('language_pair', sa.VARCHAR(
        length=32), autoincrement=False, nullable=False))
    op.drop_column('suggestions', 'source_language')
    op.drop_column('suggestions', 'target_language')
    # ### end Alembic commands ###
