"""add targetCountry column to translate table

Revision ID: b12e1fcf631b
Revises: 39f0484fb793
Create Date: 2025-10-29 12:36:01.208231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12e1fcf631b'
down_revision: Union[str, Sequence[str], None] = '39f0484fb793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate', sa.Column('targetCountry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translate', 'targetCountry')
    # ### end Alembic commands ###
